### ISSUE TITLE
Tests roadmap

### ISSUE THREAD

**Issue by debabin** [siberiacancode/reactuse#208]
- [x] https://github.com/siberiacancode/reactuse/issues/100
- [x] https://github.com/siberiacancode/reactuse/issues/261
- [x] https://github.com/siberiacancode/reactuse/issues/260
- [x] https://github.com/siberiacancode/reactuse/issues/307
- [x] https://github.com/siberiacancode/reactuse/issues/308
- [ ] https://github.com/siberiacancode/reactuse/issues/309
- [x] https://github.com/siberiacancode/reactuse/issues/37
- [ ] https://github.com/siberiacancode/reactuse/issues/43
- [x] https://github.com/siberiacancode/reactuse/issues/44
- [x] https://github.com/siberiacancode/reactuse/issues/75
- [x] https://github.com/siberiacancode/reactuse/issues/103
- [ ] https://github.com/siberiacancode/reactuse/issues/108
- [x] https://github.com/siberiacancode/reactuse/issues/95
- [ ] https://github.com/siberiacancode/reactuse/issues/98
- [x] https://github.com/siberiacancode/reactuse/issues/99
- [x] https://github.com/siberiacancode/reactuse/issues/110
- [ ] https://github.com/siberiacancode/reactuse/issues/38
- [ ] https://github.com/siberiacancode/reactuse/issues/39
- [x] https://github.com/siberiacancode/reactuse/issues/194
- [ ] https://github.com/siberiacancode/reactuse/issues/220
- [x] https://github.com/siberiacancode/reactuse/issues/193
- [ ] https://github.com/siberiacancode/reactuse/issues/221
- [x] https://github.com/siberiacancode/reactuse/issues/237
- [ ] https://github.com/siberiacancode/reactuse/issues/235
- [ ] https://github.com/siberiacancode/reactuse/issues/236
- [ ] https://github.com/siberiacancode/reactuse/issues/242
- [ ] https://github.com/siberiacancode/reactuse/issues/255
- [ ] https://github.com/siberiacancode/reactuse/issues/304
- [ ] https://github.com/siberiacancode/reactuse/issues/303
- [ ] https://github.com/siberiacancode/reactuse/issues/302
- [ ] https://github.com/siberiacancode/reactuse/issues/301
- [ ] https://github.com/siberiacancode/reactuse/issues/300
- [ ] https://github.com/siberiacancode/reactuse/issues/299
- [ ] https://github.com/siberiacancode/reactuse/issues/298
- [x] https://github.com/siberiacancode/reactuse/issues/297
- [x] https://github.com/siberiacancode/reactuse/issues/296
- [x] https://github.com/siberiacancode/reactuse/issues/295
- [x] https://github.com/siberiacancode/reactuse/issues/294
- [x] https://github.com/siberiacancode/reactuse/issues/293
- [x] https://github.com/siberiacancode/reactuse/issues/292
- [ ] https://github.com/siberiacancode/reactuse/issues/291
- [ ] https://github.com/siberiacancode/reactuse/issues/290
- [x] https://github.com/siberiacancode/reactuse/issues/289
- [ ] https://github.com/siberiacancode/reactuse/issues/288
- [ ] https://github.com/siberiacancode/reactuse/issues/158
- [x] https://github.com/siberiacancode/reactuse/issues/325
- [ ] https://github.com/siberiacancode/reactuse/issues/324
- [ ] https://github.com/siberiacancode/reactuse/issues/323
- [x] https://github.com/siberiacancode/reactuse/issues/322
- [x] https://github.com/siberiacancode/reactuse/issues/321
- [ ] https://github.com/siberiacancode/reactuse/issues/327
- [ ] https://github.com/siberiacancode/reactuse/issues/340
- [x] https://github.com/siberiacancode/reactuse/issues/341
